name: flutterdoc
description: A sample command-line application.
version: 0.0.1
homepage: https://github.com/pd4d10/flutterdoc
author: Rongjian Zhang <pd4d10@gmail.com>

environment:
  sdk: ">=2.4.0 <3.0.0"

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
