name: flutterdoc
description: A command line tool to generate gallery for your Flutter widgets.
version: 0.1.3
homepage: https://github.com/bytedance/flutterdoc
author: Rongjian Zhang <pd4d10@gmail.com>

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  path: ^1.6.0
  analyzer: ^0.37.0
  dartdoc: ^0.28.5
  yaml: ^2.2.0
  dart_style: ^1.2.10
  args: ^1.5.2
  json_annotation: ^3.0.0
  # stagehand: ^3.3.4

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
  json_serializable: ^3.2.2
  build_runner: ^1.7.0
  # source_gen: ^0.9.4

executables:
  flutterdoc: null
